spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://bookmark.cidtckobgf3m.ap-northeast-2.rds.amazonaws.com:3306/bookmark
    username: root
    password: cksdl30104
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸

jwt:
  secret:
    key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

google:
  clientId: 213617031580-3bjijd93fo1fh4jekjo088s6qbb6p6rt.apps.googleusercontent.com

cloud:
  aws:
    credentials:
      access-key: AKIA5XWIGNGXIJITOOHJ
      secret-key: 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
    s3:
      bucket: checkmark
      base-url: https://checkmark.s3.ap-northeast-2.amazonaws.com
    region:
      static: ap-northeast-2
    stack:
      auto: false